spring.application.name=skills-keeper

spring.datasource.url=jdbc:postgresql://localhost:5432/skills_keeper
spring.datasource.username=${SKILLS_KEEPER_DB_USERNAME:skills_keeper}
spring.datasource.password=${SKILLS_KEEPER_DB_PASSWORD:skills_keeper}

app.file-storage.base-dir=./data/files
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=20MB

app.auth.password.bcrypt-strength=10

app.auth.token.time-to-live=30m
app.auth.token.max-retained=10000
